//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Web.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Web.Resources.Shared.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Insurance Units System - MIUS.
        /// </summary>
        public static string AppLayoutHeaderTitle {
            get {
                return ResourceManager.GetString("AppLayoutHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://canada.ca.
        /// </summary>
        public static string AppLayoutIntranetAppSettingsURL {
            get {
                return ResourceManager.GetString("AppLayoutIntranetAppSettingsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIUS.
        /// </summary>
        public static string AppLayoutIntranetText_Banner {
            get {
                return ResourceManager.GetString("AppLayoutIntranetText_Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIUS.
        /// </summary>
        public static string AppLayoutIntranetTitle_BoldText {
            get {
                return ResourceManager.GetString("AppLayoutIntranetTitle_BoldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Administration.
        /// </summary>
        public static string AppLayoutIntranetTitle_Text {
            get {
                return ResourceManager.GetString("AppLayoutIntranetTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AppLayoutLeftMenuItem_About {
            get {
                return ResourceManager.GetString("AppLayoutLeftMenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string AppLayoutLeftMenuItem_Certs {
            get {
                return ResourceManager.GetString("AppLayoutLeftMenuItem_Certs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string AppLayoutLeftMenuItem_Counter {
            get {
                return ResourceManager.GetString("AppLayoutLeftMenuItem_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string AppLayoutLeftMenuItem_Docs {
            get {
                return ResourceManager.GetString("AppLayoutLeftMenuItem_Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Items (CRSM API).
        /// </summary>
        public static string AppLayoutLeftMenuItem_FeeItems {
            get {
                return ResourceManager.GetString("AppLayoutLeftMenuItem_FeeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch data.
        /// </summary>
        public static string AppLayoutLeftMenuItem_Fetch {
            get {
                return ResourceManager.GetString("AppLayoutLeftMenuItem_Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string AppLayoutLeftMenuItem_Help {
            get {
                return ResourceManager.GetString("AppLayoutLeftMenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment (COPS API).
        /// </summary>
        public static string AppLayoutLeftMenuItem_PaymentItems {
            get {
                return ResourceManager.GetString("AppLayoutLeftMenuItem_PaymentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessels.
        /// </summary>
        public static string AppLayoutLeftMenuItem_Vessels {
            get {
                return ResourceManager.GetString("AppLayoutLeftMenuItem_Vessels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string AppLayoutLeftMenuText_Home {
            get {
                return ResourceManager.GetString("AppLayoutLeftMenuText_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string AppLayoutLeftMenuText_Info {
            get {
                return ResourceManager.GetString("AppLayoutLeftMenuText_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string AppLayoutLeftMenuText_Tools {
            get {
                return ResourceManager.GetString("AppLayoutLeftMenuText_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Insurance Units System - MIUS.
        /// </summary>
        public static string AppLayoutTitle_Text {
            get {
                return ResourceManager.GetString("AppLayoutTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIUS.
        /// </summary>
        public static string ApplicationTitle_Acronym {
            get {
                return ResourceManager.GetString("ApplicationTitle_Acronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Breadcrumb_Home {
            get {
                return ResourceManager.GetString("Breadcrumb_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Insurance Certificate Application.
        /// </summary>
        public static string Breadcrumb_MarineInsurance {
            get {
                return ResourceManager.GetString("Breadcrumb_MarineInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1. Enter contact information.
        /// </summary>
        public static string Breadcrumb_Step1 {
            get {
                return ResourceManager.GetString("Breadcrumb_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2. Enter service request details.
        /// </summary>
        public static string Breadcrumb_Step2 {
            get {
                return ResourceManager.GetString("Breadcrumb_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3. Review request details.
        /// </summary>
        public static string Breadcrumb_Step3 {
            get {
                return ResourceManager.GetString("Breadcrumb_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4. Submit and Pay.
        /// </summary>
        public static string Breadcrumb_Step4 {
            get {
                return ResourceManager.GetString("Breadcrumb_Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Canada Services.
        /// </summary>
        public static string Breadcrumb_TCServices {
            get {
                return ResourceManager.GetString("Breadcrumb_TCServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel? any information you entered will be lost..
        /// </summary>
        public static string Dialog_ConfirmCancel {
            get {
                return ResourceManager.GetString("Dialog_ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: official number already added, duplicates not allowed..
        /// </summary>
        public static string Dialog_DuplicateOfficialNumError {
            get {
                return ResourceManager.GetString("Dialog_DuplicateOfficialNumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments and agencies.
        /// </summary>
        public static string Footer_DeptsAndAgencies {
            get {
                return ResourceManager.GetString("Footer_DeptsAndAgencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government-wide reporting.
        /// </summary>
        public static string Footer_GovtWideRep {
            get {
                return ResourceManager.GetString("Footer_GovtWideRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How government works.
        /// </summary>
        public static string Footer_HowGovtWorks {
            get {
                return ResourceManager.GetString("Footer_HowGovtWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Footer_News {
            get {
                return ResourceManager.GetString("Footer_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open government.
        /// </summary>
        public static string Footer_OpenGovt {
            get {
                return ResourceManager.GetString("Footer_OpenGovt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime Minister.
        /// </summary>
        public static string Footer_PM {
            get {
                return ResourceManager.GetString("Footer_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public service and military.
        /// </summary>
        public static string Footer_PublicSvc {
            get {
                return ResourceManager.GetString("Footer_PublicSvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treaties, laws and regulations.
        /// </summary>
        public static string Footer_Treaties {
            get {
                return ResourceManager.GetString("Footer_Treaties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Form_Back {
            get {
                return ResourceManager.GetString("Form_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel application.
        /// </summary>
        public static string Form_Cancel {
            get {
                return ResourceManager.GetString("Form_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Form_Next {
            get {
                return ResourceManager.GetString("Form_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save application and close.
        /// </summary>
        public static string Form_SaveAndClose {
            get {
                return ResourceManager.GetString("Form_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Form_Submit {
            get {
                return ResourceManager.GetString("Form_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit for payment.
        /// </summary>
        public static string Form_Submit4Payment {
            get {
                return ResourceManager.GetString("Form_Submit4Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Form_Upload {
            get {
                return ResourceManager.GetString("Form_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are mandatory unless indicated otherwise..
        /// </summary>
        public static string HeadingNote {
            get {
                return ResourceManager.GetString("HeadingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Insurance Units System.
        /// </summary>
        public static string IndexHeading {
            get {
                return ResourceManager.GetString("IndexHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the links on the left to access administrative tools..
        /// </summary>
        public static string IndexIntro {
            get {
                return ResourceManager.GetString("IndexIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Documents for MIUS.
        /// </summary>
        public static string MainLayoutDocsLink {
            get {
                return ResourceManager.GetString("MainLayoutDocsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem on this page.
        /// </summary>
        public static string MasterLayout_ReportProblem {
            get {
                return ResourceManager.GetString("MasterLayout_ReportProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this page.
        /// </summary>
        public static string MasterLayout_SharePage {
            get {
                return ResourceManager.GetString("MasterLayout_SharePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }
    }
}
