//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Web.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactInformation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactInformation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Web.Resources.Pages.ContactInformation", typeof(ContactInformation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1. Enter your contact information.
        /// </summary>
        public static string Heading1 {
            get {
                return ResourceManager.GetString("Heading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started, provide the following information.
        /// </summary>
        public static string Heading4 {
            get {
                return ResourceManager.GetString("Heading4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where would you like the certificate(s) mailed?.
        /// </summary>
        public static string MailingAddressChoice {
            get {
                return ResourceManager.GetString("MailingAddressChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use different mailing address.
        /// </summary>
        public static string MailingAddressOther {
            get {
                return ResourceManager.GetString("MailingAddressOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same address as above.
        /// </summary>
        public static string MailingAddressSame {
            get {
                return ResourceManager.GetString("MailingAddressSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing address.
        /// </summary>
        public static string MailingAddressTitle {
            get {
                return ResourceManager.GetString("MailingAddressTitle", resourceCulture);
            }
        }
    }
}
