//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressComplete.Demo.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactInfoForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactInfoForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddressComplete.Demo.Resources.Pages.ContactInfoForm", typeof(ContactInfoForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string AddressCity {
            get {
                return ResourceManager.GetString("AddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string AddressCity1 {
            get {
                return ResourceManager.GetString("AddressCity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country/Region.
        /// </summary>
        public static string AddressCountry {
            get {
                return ResourceManager.GetString("AddressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country/Region.
        /// </summary>
        public static string AddressCountry1 {
            get {
                return ResourceManager.GetString("AddressCountry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1 (CP Address lookup requires valid CP APIKey in appsettings files, under AddressApi).
        /// </summary>
        public static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1.
        /// </summary>
        public static string AddressLine11 {
            get {
                return ResourceManager.GetString("AddressLine11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2.
        /// </summary>
        public static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2.
        /// </summary>
        public static string AddressLine21 {
            get {
                return ResourceManager.GetString("AddressLine21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string AddressLine2Prefix {
            get {
                return ResourceManager.GetString("AddressLine2Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string AddressLine2Prefix1 {
            get {
                return ResourceManager.GetString("AddressLine2Prefix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Lookup.
        /// </summary>
        public static string AddressLookup {
            get {
                return ResourceManager.GetString("AddressLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Lookup.
        /// </summary>
        public static string AddressLookup1 {
            get {
                return ResourceManager.GetString("AddressLookup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results are filtered by country selected below. Defaults to Canada when empty..
        /// </summary>
        public static string AddressLookupFooterNote {
            get {
                return ResourceManager.GetString("AddressLookupFooterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results are filtered by country selected below. Defaults to Canada when empty..
        /// </summary>
        public static string AddressLookupFooterNote1 {
            get {
                return ResourceManager.GetString("AddressLookupFooterNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing your address....
        /// </summary>
        public static string AddressLookupPlaceholder {
            get {
                return ResourceManager.GetString("AddressLookupPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing your address....
        /// </summary>
        public static string AddressLookupPlaceholder1 {
            get {
                return ResourceManager.GetString("AddressLookupPlaceholder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal/ZIP Code.
        /// </summary>
        public static string AddressPostalCode {
            get {
                return ResourceManager.GetString("AddressPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal/ZIP Code.
        /// </summary>
        public static string AddressPostalCode1 {
            get {
                return ResourceManager.GetString("AddressPostalCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province/State/Territory.
        /// </summary>
        public static string AddressProvince {
            get {
                return ResourceManager.GetString("AddressProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province/State/Territory.
        /// </summary>
        public static string AddressProvince1 {
            get {
                return ResourceManager.GetString("AddressProvince1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business number.
        /// </summary>
        public static string BusinessNumber {
            get {
                return ResourceManager.GetString("BusinessNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business name.
        /// </summary>
        public static string CompanyName1 {
            get {
                return ResourceManager.GetString("CompanyName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your contact information.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your contact information.
        /// </summary>
        public static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Email1 {
            get {
                return ResourceManager.GetString("Email1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will use your email address to communicate the status of your request.
        /// </summary>
        public static string EmailNote {
            get {
                return ResourceManager.GetString("EmailNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will use your email address to communicate the status of your request.
        /// </summary>
        public static string EmailNote1 {
            get {
                return ResourceManager.GetString("EmailNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string ExtNumber {
            get {
                return ResourceManager.GetString("ExtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string ExtNumber1 {
            get {
                return ResourceManager.GetString("ExtNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName1 {
            get {
                return ResourceManager.GetString("FirstName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName1 {
            get {
                return ResourceManager.GetString("LastName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number.
        /// </summary>
        public static string PhoneNumber1 {
            get {
                return ResourceManager.GetString("PhoneNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing your address....
        /// </summary>
        public static string PlaceholderTyping {
            get {
                return ResourceManager.GetString("PlaceholderTyping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing your address....
        /// </summary>
        public static string PlaceholderTyping1 {
            get {
                return ResourceManager.GetString("PlaceholderTyping1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select1 {
            get {
                return ResourceManager.GetString("Select1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Info.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Info.
        /// </summary>
        public static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
    }
}
